name: publish

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created || false }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v5
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json

  publish-package:
    name: publish-package
    runs-on: ubuntu-latest
    needs:
      - release-please
    permissions:
      id-token: write
    if: needs.release-please.outputs.release-created == 'true'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      - run: |
          PUBLISH_VERSION=${{ needs.release-please.outputs.tag-name }}
          echo "PUBLISH_VERSION=${PUBLISH_VERSION#v}.0" >> $GITHUB_ENV
      - run: dotnet publish --configuration Release MediaDataHubPlugin.sln /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /property:Version=${PUBLISH_VERSION}
      - run: sudo apt-get install -y jq
      - run: |
          jq -c ".version = \"${PUBLISH_VERSION}\" | .timestamp = \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"" meta.template.json > meta.json
          mv ./MediaDataHub.Plugin/bin/Release/net9.0/publish/MediaDataHub.Plugin.dll MediaDataHub.Plugin.dll
          zip -r media-data-hub.zip meta.json MediaDataHub.Plugin.dll
          md5sum media-data-hub.zip | head -c 32 > checksum
      - run: gh release upload ${{ needs.release-please.outputs.tag-name }} media-data-hub.zip checksum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
